# Generated by Django 5.1.8 on 2025-05-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='version',
        ),
        migrations.AddField(
            model_name='installedapplication',
            name='version',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
