# generated by datamodel-codegen:
#   filename:  properties_directory/structural/basis/atomic_element.json
#   version:   0.28.5

from __future__ import annotations

from pydantic import BaseModel


class AtomicElementSchema(BaseModel):
    value: str
    """
    value of this entry
    """
    id: int
    """
    integer id of this entry
    """
