# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: repeated_duration_timestamp.proto
# plugin: python-betterproto
# This file has been @generated

__all__ = ("Test",)


from datetime import datetime, timedelta
from typing import (
    List,
)

from pydantic.dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto.Message):
    """ """

    times: List[datetime] = betterproto.message_field(1)
    """
    
    """

    durations: List[timedelta] = betterproto.message_field(2)
    """
    
    """
