# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from global_vo_grpc_service.protos import team_api_pb2 as global__vo__grpc__service_dot_protos_dot_team__api__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class TeamApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTeam = channel.unary_unary(
                '/TeamApi/CreateTeam',
                request_serializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.CreateTeamRequest.SerializeToString,
                response_deserializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.CreateTeamResponse.FromString,
                )
        self.FindTeamById = channel.unary_unary(
                '/TeamApi/FindTeamById',
                request_serializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.FindTeamByIdRequest.SerializeToString,
                response_deserializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.FindTeamByIdResponse.FromString,
                )
        self.ListTeams = channel.unary_unary(
                '/TeamApi/ListTeams',
                request_serializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.ListTeamsRequest.SerializeToString,
                response_deserializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.ListTeamsResponse.FromString,
                )
        self.ListCurrentUsersTeams = channel.unary_unary(
                '/TeamApi/ListCurrentUsersTeams',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.ListCurrentUsersTeamsResponse.FromString,
                )
        self.ListTeamCardsByUserId = channel.unary_unary(
                '/TeamApi/ListTeamCardsByUserId',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.ListTeamCardsByUserIdResponse.FromString,
                )
        self.UpdateTeam = channel.unary_unary(
                '/TeamApi/UpdateTeam',
                request_serializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.UpdateTeamRequest.SerializeToString,
                response_deserializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.UpdateTeamResponse.FromString,
                )


class TeamApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindTeamById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTeams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCurrentUsersTeams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTeamCardsByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TeamApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTeam,
                    request_deserializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.CreateTeamRequest.FromString,
                    response_serializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.CreateTeamResponse.SerializeToString,
            ),
            'FindTeamById': grpc.unary_unary_rpc_method_handler(
                    servicer.FindTeamById,
                    request_deserializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.FindTeamByIdRequest.FromString,
                    response_serializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.FindTeamByIdResponse.SerializeToString,
            ),
            'ListTeams': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTeams,
                    request_deserializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.ListTeamsRequest.FromString,
                    response_serializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.ListTeamsResponse.SerializeToString,
            ),
            'ListCurrentUsersTeams': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCurrentUsersTeams,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.ListCurrentUsersTeamsResponse.SerializeToString,
            ),
            'ListTeamCardsByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTeamCardsByUserId,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.ListTeamCardsByUserIdResponse.SerializeToString,
            ),
            'UpdateTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTeam,
                    request_deserializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.UpdateTeamRequest.FromString,
                    response_serializer=global__vo__grpc__service_dot_protos_dot_team__api__pb2.UpdateTeamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TeamApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TeamApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamApi/CreateTeam',
            global__vo__grpc__service_dot_protos_dot_team__api__pb2.CreateTeamRequest.SerializeToString,
            global__vo__grpc__service_dot_protos_dot_team__api__pb2.CreateTeamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindTeamById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamApi/FindTeamById',
            global__vo__grpc__service_dot_protos_dot_team__api__pb2.FindTeamByIdRequest.SerializeToString,
            global__vo__grpc__service_dot_protos_dot_team__api__pb2.FindTeamByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTeams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamApi/ListTeams',
            global__vo__grpc__service_dot_protos_dot_team__api__pb2.ListTeamsRequest.SerializeToString,
            global__vo__grpc__service_dot_protos_dot_team__api__pb2.ListTeamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListCurrentUsersTeams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamApi/ListCurrentUsersTeams',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            global__vo__grpc__service_dot_protos_dot_team__api__pb2.ListCurrentUsersTeamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTeamCardsByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamApi/ListTeamCardsByUserId',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            global__vo__grpc__service_dot_protos_dot_team__api__pb2.ListTeamCardsByUserIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TeamApi/UpdateTeam',
            global__vo__grpc__service_dot_protos_dot_team__api__pb2.UpdateTeamRequest.SerializeToString,
            global__vo__grpc__service_dot_protos_dot_team__api__pb2.UpdateTeamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
