# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: bool.proto
# plugin: python-betterproto
# This file has been @generated

__all__ = ("Test",)


from pydantic.dataclasses import dataclass

import betterproto_fw


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto_fw.Message):
    """ """

    value: bool = betterproto_fw.bool_field(1)
    """
    
    """
