# Code generated by TRAC

import typing as _tp  # noqa
import dataclasses as _dc  # noqa
import enum as _enum  # noqa

import tracdap.rt.metadata as metadata



@_dc.dataclass
class _ConfigFile:

    config: "_tp.Dict[str, str]" = _dc.field(default_factory=dict)


@_dc.dataclass
class PluginConfig:

    protocol: "str" = ""

    publicProperties: "_tp.Dict[str, str]" = _dc.field(default_factory=dict)

    properties: "_tp.Dict[str, str]" = _dc.field(default_factory=dict)

    secrets: "_tp.Dict[str, str]" = _dc.field(default_factory=dict)


@_dc.dataclass
class PlatformInfo:

    environment: "str" = ""

    production: "bool" = False

    deploymentInfo: "_tp.Dict[str, str]" = _dc.field(default_factory=dict)


@_dc.dataclass
class StorageConfig:

    buckets: "_tp.Dict[str, PluginConfig]" = _dc.field(default_factory=dict)

    """TODO: Rename "buckets" as "internal" for 0.7"""

    external: "_tp.Dict[str, PluginConfig]" = _dc.field(default_factory=dict)

    defaultBucket: "str" = ""

    defaultFormat: "str" = ""

    defaultLayout: "metadata.StorageLayout" = metadata.StorageLayout.OBJECT_ID_LAYOUT


@_dc.dataclass
class ServiceConfig:

    enabled: "_tp.Optional[bool]" = None

    alias: "str" = ""

    port: "int" = 0

    properties: "_tp.Dict[str, str]" = _dc.field(default_factory=dict)
