# Generated by Django 5.1.7 on 2025-04-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_bandmember_photo_url_concert_cover_photo_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillist",
            name="first_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
