# Generated by Django 5.2.1 on 2025-05-15 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomMenuUrl",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("custom_url", models.CharField(max_length=255)),
                ("open_in_new_tab", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Custom Menu URL",
                "verbose_name_plural": "Custom Menu URLs",
                "db_table": "wagtailmenupage_custom_menu_url",
            },
            bases=("wagtailcore.page",),
        ),
    ]
