# Generated by Django 3.2.14 on 2024-05-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maji_passport', '0006_auto_20240521_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportuser',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='passportuser',
            name='cover_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='passportuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='passportuser',
            name='social_networks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
