# Generated by Django 3.2.14 on 2024-05-30 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maji_passport', '0007_auto_20240522_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportuser',
            name='argo_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passport_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
