/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class hand_debug_data_lcmt implements lcm.lcm.LCMEncodable
{
    public byte joint_error_code[];
    public byte joint_status[];
    public float joint_curPos[];
    public float joint_force[];
    public float joint_current[];
 
    public hand_debug_data_lcmt()
    {
        joint_error_code = new byte[12];
        joint_status = new byte[12];
        joint_curPos = new float[12];
        joint_force = new float[12];
        joint_current = new float[12];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x355600c11bc3caa9L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.hand_debug_data_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.hand_debug_data_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.write(this.joint_error_code, 0, 12);
 
        outs.write(this.joint_status, 0, 12);
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_curPos[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_force[a]); 
        }
 
        for (int a = 0; a < 12; a++) {
            outs.writeFloat(this.joint_current[a]); 
        }
 
    }
 
    public hand_debug_data_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public hand_debug_data_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.hand_debug_data_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.hand_debug_data_lcmt o = new lcmtypes.hand_debug_data_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.joint_error_code = new byte[(int) 12];
        ins.readFully(this.joint_error_code, 0, 12); 
        this.joint_status = new byte[(int) 12];
        ins.readFully(this.joint_status, 0, 12); 
        this.joint_curPos = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_curPos[a] = ins.readFloat();
        }
 
        this.joint_force = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_force[a] = ins.readFloat();
        }
 
        this.joint_current = new float[(int) 12];
        for (int a = 0; a < 12; a++) {
            this.joint_current[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.hand_debug_data_lcmt copy()
    {
        lcmtypes.hand_debug_data_lcmt outobj = new lcmtypes.hand_debug_data_lcmt();
        outobj.joint_error_code = new byte[(int) 12];
        System.arraycopy(this.joint_error_code, 0, outobj.joint_error_code, 0, 12); 
        outobj.joint_status = new byte[(int) 12];
        System.arraycopy(this.joint_status, 0, outobj.joint_status, 0, 12); 
        outobj.joint_curPos = new float[(int) 12];
        System.arraycopy(this.joint_curPos, 0, outobj.joint_curPos, 0, 12); 
        outobj.joint_force = new float[(int) 12];
        System.arraycopy(this.joint_force, 0, outobj.joint_force, 0, 12); 
        outobj.joint_current = new float[(int) 12];
        System.arraycopy(this.joint_current, 0, outobj.joint_current, 0, 12); 
        return outobj;
    }
 
}

