/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class microstrain_lcmt implements lcm.lcm.LCMEncodable
{
    public float omega[];
    public float acc[];
    public float temp;
    public long good_packets;
    public long bad_packets;
    public float navQuat[];
    public float navOmega[];
    public float navRPY[];
 
    public microstrain_lcmt()
    {
        omega = new float[3];
        acc = new float[3];
        navQuat = new float[4];
        navOmega = new float[3];
        navRPY = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x491dbdb1d605c43aL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.microstrain_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.microstrain_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.omega[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.acc[a]); 
        }
 
        outs.writeFloat(this.temp); 
 
        outs.writeLong(this.good_packets); 
 
        outs.writeLong(this.bad_packets); 
 
        for (int a = 0; a < 4; a++) {
            outs.writeFloat(this.navQuat[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.navOmega[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.navRPY[a]); 
        }
 
    }
 
    public microstrain_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public microstrain_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.microstrain_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.microstrain_lcmt o = new lcmtypes.microstrain_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.omega = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.omega[a] = ins.readFloat();
        }
 
        this.acc = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.acc[a] = ins.readFloat();
        }
 
        this.temp = ins.readFloat();
 
        this.good_packets = ins.readLong();
 
        this.bad_packets = ins.readLong();
 
        this.navQuat = new float[(int) 4];
        for (int a = 0; a < 4; a++) {
            this.navQuat[a] = ins.readFloat();
        }
 
        this.navOmega = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.navOmega[a] = ins.readFloat();
        }
 
        this.navRPY = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.navRPY[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.microstrain_lcmt copy()
    {
        lcmtypes.microstrain_lcmt outobj = new lcmtypes.microstrain_lcmt();
        outobj.omega = new float[(int) 3];
        System.arraycopy(this.omega, 0, outobj.omega, 0, 3); 
        outobj.acc = new float[(int) 3];
        System.arraycopy(this.acc, 0, outobj.acc, 0, 3); 
        outobj.temp = this.temp;
 
        outobj.good_packets = this.good_packets;
 
        outobj.bad_packets = this.bad_packets;
 
        outobj.navQuat = new float[(int) 4];
        System.arraycopy(this.navQuat, 0, outobj.navQuat, 0, 4); 
        outobj.navOmega = new float[(int) 3];
        System.arraycopy(this.navOmega, 0, outobj.navOmega, 0, 3); 
        outobj.navRPY = new float[(int) 3];
        System.arraycopy(this.navRPY, 0, outobj.navRPY, 0, 3); 
        return outobj;
    }
 
}

