# generated by datamodel-codegen:
#   filename:  materials_category/defects/enums/coordinates_shape.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class CoordinatesShape(Enum):
    sphere = "sphere"
    cylinder = "cylinder"
    rectangle = "rectangle"
    triangular_prism = "triangular_prism"


class CoordinatesShapeEnum(BaseModel):
    coordinatesShape: Optional[CoordinatesShape] = None
