/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class dcm_arm_control_lcmt implements lcm.lcm.LCMEncodable
{
    public float p_WArmEndL_ref[];
    public float p_WArmEndL_act[];
    public float p_WArmEndR_ref[];
    public float p_WArmEndR_act[];
    public float v_WArmEndL_ref[];
    public float v_WArmEndL_act[];
    public float v_WArmEndR_ref[];
    public float v_WArmEndR_act[];
    public float rpy_WArmEndL_ref[];
    public float rpy_WArmEndL_act[];
    public float rpy_WArmEndR_ref[];
    public float rpy_WArmEndR_act[];
    public float w_WArmEndL_ref[];
    public float w_WArmEndL_act[];
    public float w_WArmEndR_ref[];
    public float w_WArmEndR_act[];
 
    public dcm_arm_control_lcmt()
    {
        p_WArmEndL_ref = new float[3];
        p_WArmEndL_act = new float[3];
        p_WArmEndR_ref = new float[3];
        p_WArmEndR_act = new float[3];
        v_WArmEndL_ref = new float[3];
        v_WArmEndL_act = new float[3];
        v_WArmEndR_ref = new float[3];
        v_WArmEndR_act = new float[3];
        rpy_WArmEndL_ref = new float[3];
        rpy_WArmEndL_act = new float[3];
        rpy_WArmEndR_ref = new float[3];
        rpy_WArmEndR_act = new float[3];
        w_WArmEndL_ref = new float[3];
        w_WArmEndL_act = new float[3];
        w_WArmEndR_ref = new float[3];
        w_WArmEndR_act = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x318414332ce70483L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.dcm_arm_control_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.dcm_arm_control_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.p_WArmEndL_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.p_WArmEndL_act[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.p_WArmEndR_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.p_WArmEndR_act[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.v_WArmEndL_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.v_WArmEndL_act[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.v_WArmEndR_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.v_WArmEndR_act[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.rpy_WArmEndL_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.rpy_WArmEndL_act[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.rpy_WArmEndR_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.rpy_WArmEndR_act[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.w_WArmEndL_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.w_WArmEndL_act[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.w_WArmEndR_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.w_WArmEndR_act[a]); 
        }
 
    }
 
    public dcm_arm_control_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public dcm_arm_control_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.dcm_arm_control_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.dcm_arm_control_lcmt o = new lcmtypes.dcm_arm_control_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.p_WArmEndL_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.p_WArmEndL_ref[a] = ins.readFloat();
        }
 
        this.p_WArmEndL_act = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.p_WArmEndL_act[a] = ins.readFloat();
        }
 
        this.p_WArmEndR_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.p_WArmEndR_ref[a] = ins.readFloat();
        }
 
        this.p_WArmEndR_act = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.p_WArmEndR_act[a] = ins.readFloat();
        }
 
        this.v_WArmEndL_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.v_WArmEndL_ref[a] = ins.readFloat();
        }
 
        this.v_WArmEndL_act = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.v_WArmEndL_act[a] = ins.readFloat();
        }
 
        this.v_WArmEndR_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.v_WArmEndR_ref[a] = ins.readFloat();
        }
 
        this.v_WArmEndR_act = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.v_WArmEndR_act[a] = ins.readFloat();
        }
 
        this.rpy_WArmEndL_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rpy_WArmEndL_ref[a] = ins.readFloat();
        }
 
        this.rpy_WArmEndL_act = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rpy_WArmEndL_act[a] = ins.readFloat();
        }
 
        this.rpy_WArmEndR_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rpy_WArmEndR_ref[a] = ins.readFloat();
        }
 
        this.rpy_WArmEndR_act = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.rpy_WArmEndR_act[a] = ins.readFloat();
        }
 
        this.w_WArmEndL_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.w_WArmEndL_ref[a] = ins.readFloat();
        }
 
        this.w_WArmEndL_act = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.w_WArmEndL_act[a] = ins.readFloat();
        }
 
        this.w_WArmEndR_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.w_WArmEndR_ref[a] = ins.readFloat();
        }
 
        this.w_WArmEndR_act = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.w_WArmEndR_act[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.dcm_arm_control_lcmt copy()
    {
        lcmtypes.dcm_arm_control_lcmt outobj = new lcmtypes.dcm_arm_control_lcmt();
        outobj.p_WArmEndL_ref = new float[(int) 3];
        System.arraycopy(this.p_WArmEndL_ref, 0, outobj.p_WArmEndL_ref, 0, 3); 
        outobj.p_WArmEndL_act = new float[(int) 3];
        System.arraycopy(this.p_WArmEndL_act, 0, outobj.p_WArmEndL_act, 0, 3); 
        outobj.p_WArmEndR_ref = new float[(int) 3];
        System.arraycopy(this.p_WArmEndR_ref, 0, outobj.p_WArmEndR_ref, 0, 3); 
        outobj.p_WArmEndR_act = new float[(int) 3];
        System.arraycopy(this.p_WArmEndR_act, 0, outobj.p_WArmEndR_act, 0, 3); 
        outobj.v_WArmEndL_ref = new float[(int) 3];
        System.arraycopy(this.v_WArmEndL_ref, 0, outobj.v_WArmEndL_ref, 0, 3); 
        outobj.v_WArmEndL_act = new float[(int) 3];
        System.arraycopy(this.v_WArmEndL_act, 0, outobj.v_WArmEndL_act, 0, 3); 
        outobj.v_WArmEndR_ref = new float[(int) 3];
        System.arraycopy(this.v_WArmEndR_ref, 0, outobj.v_WArmEndR_ref, 0, 3); 
        outobj.v_WArmEndR_act = new float[(int) 3];
        System.arraycopy(this.v_WArmEndR_act, 0, outobj.v_WArmEndR_act, 0, 3); 
        outobj.rpy_WArmEndL_ref = new float[(int) 3];
        System.arraycopy(this.rpy_WArmEndL_ref, 0, outobj.rpy_WArmEndL_ref, 0, 3); 
        outobj.rpy_WArmEndL_act = new float[(int) 3];
        System.arraycopy(this.rpy_WArmEndL_act, 0, outobj.rpy_WArmEndL_act, 0, 3); 
        outobj.rpy_WArmEndR_ref = new float[(int) 3];
        System.arraycopy(this.rpy_WArmEndR_ref, 0, outobj.rpy_WArmEndR_ref, 0, 3); 
        outobj.rpy_WArmEndR_act = new float[(int) 3];
        System.arraycopy(this.rpy_WArmEndR_act, 0, outobj.rpy_WArmEndR_act, 0, 3); 
        outobj.w_WArmEndL_ref = new float[(int) 3];
        System.arraycopy(this.w_WArmEndL_ref, 0, outobj.w_WArmEndL_ref, 0, 3); 
        outobj.w_WArmEndL_act = new float[(int) 3];
        System.arraycopy(this.w_WArmEndL_act, 0, outobj.w_WArmEndL_act, 0, 3); 
        outobj.w_WArmEndR_ref = new float[(int) 3];
        System.arraycopy(this.w_WArmEndR_ref, 0, outobj.w_WArmEndR_ref, 0, 3); 
        outobj.w_WArmEndR_act = new float[(int) 3];
        System.arraycopy(this.w_WArmEndR_act, 0, outobj.w_WArmEndR_act, 0, 3); 
        return outobj;
    }
 
}

