# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: regression_414.proto
# plugin: python-betterproto
# This file has been @generated

__all__ = ("Test",)


from dataclasses import dataclass
from typing import (
    List,
)

import betterproto_fw


@dataclass(eq=False, repr=False)
class Test(betterproto_fw.Message):
    """ """

    body: bytes = betterproto_fw.bytes_field(1)
    """
    
    """

    auth: bytes = betterproto_fw.bytes_field(2)
    """
    
    """

    signatures: List[bytes] = betterproto_fw.bytes_field(3)
    """
    
    """
