# Generated by Django 3.2.14 on 2024-05-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maji_passport', '0003_accesstoken_passport_ac_token_cccee9_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='passport_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maji_passport.passportuser'),
        ),
    ]
