# Generated by Django 3.2.14 on 2024-07-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maji_passport', '0009_auto_20240603_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportuser',
            name='social_networks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
