# Generated by Django 3.2.25 on 2024-07-22 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maji_passport', '0011_auto_20240710_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='token_expiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blacklisttoken',
            name='token_expiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
