# Generated by Django 4.2.14 on 2024-09-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maji_passport', '0012_auto_20240722_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportuser',
            name='passport_uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
