"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from compass_api_sdk.types import BaseModel
from compass_api_sdk.utils import FieldMetadata, QueryParamMetadata
from enum import Enum
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class MorphoMarketPositionChain(str, Enum):
    ETHEREUM_MAINNET = "ethereum:mainnet"
    BASE_MAINNET = "base:mainnet"


class MorphoMarketPositionRequestTypedDict(TypedDict):
    chain: NotRequired[MorphoMarketPositionChain]
    user_address: str
    unique_market_key: str


class MorphoMarketPositionRequest(BaseModel):
    chain: Annotated[
        Optional[MorphoMarketPositionChain],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = MorphoMarketPositionChain.ETHEREUM_MAINNET

    user_address: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = "0xa829B388A3DF7f581cE957a95edbe419dd146d1B"

    unique_market_key: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = "0xe7399fdebc318d76dfec7356caafcf8cd4b91287e139a3ec423f09aeeb656fc4"
