"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from compass_api_sdk.types import BaseModel
from compass_api_sdk.utils import FieldMetadata, QueryParamMetadata
from enum import Enum
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class MorphoVaultPositionChain(str, Enum):
    ETHEREUM_MAINNET = "ethereum:mainnet"
    BASE_MAINNET = "base:mainnet"


class MorphoVaultPositionRequestTypedDict(TypedDict):
    chain: NotRequired[MorphoVaultPositionChain]
    user_address: str
    vault_address: str


class MorphoVaultPositionRequest(BaseModel):
    chain: Annotated[
        Optional[MorphoVaultPositionChain],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = MorphoVaultPositionChain.ETHEREUM_MAINNET

    user_address: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = "0xa829B388A3DF7f581cE957a95edbe419dd146d1B"

    vault_address: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = "0xbEef047a543E45807105E51A8BBEFCc5950fcfBa"
