# -*- coding: utf-8 -*-

"""
verizon

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ETXResponseError(object):

    """Implementation of the 'ETXResponseError' model.

    error response structure

    Attributes:
        error (str): The short summary of the error
        description (str): The detailed description of the error

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "error": 'error',
        "description": 'description'
    }

    def __init__(self,
                 error=None,
                 description=None):
        """Constructor for the ETXResponseError class"""

        # Initialize members of the class
        self.error = error 
        self.description = description 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        error = dictionary.get("error") if dictionary.get("error") else None
        description = dictionary.get("description") if dictionary.get("description") else None
        # Return an object of this model
        return cls(error,
                   description)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'error={self.error!r}, '
                f'description={self.description!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'error={self.error!s}, '
                f'description={self.description!s})')
