# This file automatically generated by
#    /home/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/py-client/couchbase_version.py
# at
#    2025-05-15 16:05:04.315872
__version__ = '4.3.6'