# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TransactionTypeEnum(object):

    """Implementation of the 'TransactionType' enum.

    DepositTransaction Type

    Attributes:
        CHECK: The enum member of type str.
        WITHDRAWAL: The enum member of type str.
        TRANSFER: The enum member of type str.
        POSDEBIT: The enum member of type str.
        ATMWITHDRAWAL: The enum member of type str.
        BILLPAYMENT: The enum member of type str.
        FEE: The enum member of type str.
        DEPOSIT: The enum member of type str.
        ADJUSTMENT: The enum member of type str.
        INTEREST: The enum member of type str.
        DIVIDEND: The enum member of type str.
        DIRECTDEPOSIT: The enum member of type str.
        ATMDEPOSIT: The enum member of type str.
        POSCREDIT: The enum member of type str.

    """
    _all_values = ['CHECK', 'WITHDRAWAL', 'TRANSFER', 'POSDEBIT', 'ATMWITHDRAWAL', 'BILLPAYMENT', 'FEE', 'DEPOSIT', 'ADJUSTMENT', 'INTEREST', 'DIVIDEND', 'DIRECTDEPOSIT', 'ATMDEPOSIT', 'POSCREDIT']
    CHECK = 'CHECK'

    WITHDRAWAL = 'WITHDRAWAL'

    TRANSFER = 'TRANSFER'

    POSDEBIT = 'POSDEBIT'

    ATMWITHDRAWAL = 'ATMWITHDRAWAL'

    BILLPAYMENT = 'BILLPAYMENT'

    FEE = 'FEE'

    DEPOSIT = 'DEPOSIT'

    ADJUSTMENT = 'ADJUSTMENT'

    INTEREST = 'INTEREST'

    DIVIDEND = 'DIVIDEND'

    DIRECTDEPOSIT = 'DIRECTDEPOSIT'

    ATMDEPOSIT = 'ATMDEPOSIT'

    POSCREDIT = 'POSCREDIT'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   