from setuptools import setup, find_packages

setup(
    name="finance-news-api",
    version="1.0.6",
    author="Pratyush Khanal",
    author_email="pratyushkhanal@gmail.com",
    description="A powerful API that aggregates financial news and provides comprehensive market sentiment analysis",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/pratyushkhanal/finance-news-api",
    project_urls={
        "Bug Tracker": "https://github.com/pratyushkhanal/finance-news-api/issues",
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Financial and Insurance Industry",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Operating System :: OS Independent",
    ],
    packages=find_packages(include=['newsapi2', 'newsapi2.*']),
    python_requires=">=3.8",
    license="Apache-2.0",
    include_package_data=True,
    install_requires=[
        "fastapi>=0.68.0",
        "uvicorn>=0.15.0",
        "python-dotenv>=0.19.0",
        "peewee>=3.14.0",
        "pydantic>=2.0.0",
        "requests>=2.26.0",
        "beautifulsoup4>=4.9.3",
        "feedparser>=6.0.8",
        "pandas>=1.3.0",
        "numpy>=1.21.0",
        "textblob>=0.15.3",
        "python-jose[cryptography]>=3.3.0",
        "passlib[bcrypt]>=1.7.4",
        "python-multipart>=0.0.5",
        "aiohttp>=3.8.0",
        "playwright>=1.0.0",
        "curl-cffi>=0.5.0",
        "sqlalchemy>=2.0.0",
        "email-validator>=2.0.0",
        "yfinance>=0.2.0",
    ],
    extras_require={
        "dev": [
            "pytest",
            "httpx",
            "pytest-asyncio",
            "pytest-mock",
            "pytest-cov",
            "aioresponses",
            "responses",
        ],
    },
    entry_points={
        "console_scripts": [
            "finance-news-api=newsapi2.main:run_app",
        ],
    },
)
