# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(os.path.abspath("./_ext"))
from portmod.globals import get_authors, get_version  # noqa

year = datetime.now().year


# -- Project information -----------------------------------------------------

project = "Portmod"
copyright = f"2019-{year}, Portmod Authors"
authors = get_authors()
author = ", ".join(authors)

# The short X.Y version
version = f"Portmod {get_version()}"

# The full version, including alpha/beta/rc tags
release = f"Portmod {get_version()}"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "autodocsumm",
    "sphinx.ext.autodoc",
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx_autodoc_typehints",
    "sphinx.ext.intersphinx",
    "sphinxarg.ext",
    "sphinxcontrib.apidoc",
    "summary",
]

# Don't require rtd_theme when building manpages
try:
    import sphinx_rtd_theme  # noqa: F401

    extensions.append("sphinx_rtd_theme")
except ModuleNotFoundError:
    pass

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "sphinx_rtd_theme"

html_theme_options = {
    "navigation_depth": -1,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# These paths are either relative to html_static_path
# or fully qualified paths (eg. https://...)
html_css_files = [
    "css/custom.css",
]


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
always_document_param_types = True

# API docs

apidoc_module_dir = "../pybuild"
apidoc_output_dir = "dev/pybuild"
apidoc_separate_modules = True
apidoc_toc_file = False
apidoc_extra_args = ["-t=_templates"]
autodoc_default_options = {
    "autosummary": True,
}

man_pages = [
    ("cli/inquisitor", "inquisitor", "CLI QA tool", authors, 1),
    ("cli/portmod", "portmod", "Main portmod CLI interface", authors, 1),
    ("config/index", "portmod", "Configuration files for portmod", authors, 5),
    ("concepts/index", "portmod", "Portmod Concepts", authors, 7),
    ("dev/packages", "pybuild", "Portmod Packaging Guide", authors, 7),
    # This is also included in pybuild.7
    # There isn't a clear way to exclude it, and it's not clear that moving
    # it outside the packaging guide would be a better structure outside of for man pages
    ("dev/pybuild/pybuild", "pybuild", "Pybuild API", authors, 3),
    ("dev/repo/index", "pybuild", "Portmod Repositories and related files", authors, 5),
]
man_make_section_directory = True

# Issues will be caught when making the HTML doc. We need to ignore certain parts of the doc to
# avoid adding extra dependencies.
suppress_warnings = ["toc.excluded"]
