
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-18T02:35:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cc43efa2f524c91686c29a51b04e31e47206dec8",
 "version": "1.5.dev2520"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
