# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: mapmessage.proto
# plugin: python-betterproto
# This file has been @generated

__all__ = (
    "Test",
    "Nested",
)


from dataclasses import dataclass
from typing import (
    Dict,
)

import betterproto_fw


@dataclass(eq=False, repr=False)
class Test(betterproto_fw.Message):
    """ """

    items: Dict[str, "Nested"] = betterproto_fw.map_field(
        1, betterproto_fw.TYPE_STRING, betterproto_fw.TYPE_MESSAGE
    )
    """
    
    """


@dataclass(eq=False, repr=False)
class Nested(betterproto_fw.Message):
    """ """

    count: int = betterproto_fw.int32_field(1)
    """
    
    """
