# Generated by Django 5.0.3 on 2025-03-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bandmember_concert_emaillist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmember',
            name='photo_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='concert',
            name='cover_photo_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='cover_photo_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
