# Generated by Django 5.1.7 on 2025-04-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_inquiry"),
    ]

    operations = [
    ]
