
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-16T00:07:34+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "b0f1be44bdca521ed5db09eda7779080318a5cca",
 "version": "6.29.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
