# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from akoyaapisv240.api_helper import APIHelper
from akoyaapisv240.models.investment_account import InvestmentAccount


class Account3(object):

    """Implementation of the 'Account3' model.

    Attributes:
        investment_account (InvestmentAccount): Investment Account

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "investment_account": 'investmentAccount'
    }

    _optionals = [
        'investment_account',
    ]

    def __init__(self,
                 investment_account=APIHelper.SKIP):
        """Constructor for the Account3 class"""

        # Initialize members of the class
        if investment_account is not APIHelper.SKIP:
            self.investment_account = investment_account 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        investment_account = InvestmentAccount.from_dictionary(dictionary.get('investmentAccount')) if 'investmentAccount' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(investment_account)

    @classmethod
    def validate(cls, dictionary):
        """Validates dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """

        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'investment_account={(self.investment_account if hasattr(self, "investment_account") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'investment_account={(self.investment_account if hasattr(self, "investment_account") else None)!s})')
