# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SecurityIdTypeEnum(object):

    """Implementation of the 'SecurityIdType' enum.

    Security identifier type

    Attributes:
        CUSIP: The enum member of type str.
        ISIN: The enum member of type str.
        SEDOL: The enum member of type str.
        SICC: The enum member of type str.
        VALOR: The enum member of type str.
        WKN: The enum member of type str.

    """
    _all_values = ['CUSIP', 'ISIN', 'SEDOL', 'SICC', 'VALOR', 'WKN']
    CUSIP = 'CUSIP'

    ISIN = 'ISIN'

    SEDOL = 'SEDOL'

    SICC = 'SICC'

    VALOR = 'VALOR'

    WKN = 'WKN'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   