# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StockTypeEnum(object):

    """Implementation of the 'StockType' enum.

    Attributes:
        BOND: The enum member of type str.
        DEBT: The enum member of type str.
        MUTUALFUND: The enum member of type str.
        OPTION: The enum member of type str.
        OTHER: The enum member of type str.
        STOCK: The enum member of type str.
        SWEEP: The enum member of type str.

    """
    _all_values = ['BOND', 'DEBT', 'MUTUALFUND', 'OPTION', 'OTHER', 'STOCK', 'SWEEP']
    BOND = 'BOND'

    DEBT = 'DEBT'

    MUTUALFUND = 'MUTUALFUND'

    OPTION = 'OPTION'

    OTHER = 'OTHER'

    STOCK = 'STOCK'

    SWEEP = 'SWEEP'

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   