"""Generated Schema.org models using msgspec."""

from . import action
from . import creativework
from . import event
from . import intangible
from . import misc
from . import organization
from . import person
from . import place
from . import product
from . import thing

# Import all classes directly
from .action import *
from .creativework import *
from .event import *
from .intangible import *
from .misc import *
from .organization import *
from .person import *
from .place import *
from .product import *
from .thing import *

__all__ = [
    'action',
    'creativework',
    'event',
    'intangible',
    'misc',
    'organization',
    'person',
    'place',
    'product',
    'thing',
    'Model3DModel',
    'AMRadioChannel',
    'APIReference',
    'AboutPage',
    'AcceptAction',
    'Accommodation',
    'AccountingService',
    'AchieveAction',
    'Action',
    'ActionAccessSpecification',
    
    'ActivateAction',
    'AddAction',
    'AdministrativeArea',
    'AdultEntertainment',
    
    'AdvertiserContentArticle',
    'AggregateOffer',
    'AggregateRating',
    'AgreeAction',
    'Airline',
    'Airport',
    'AlignmentObject',
    'AllocateAction',
    'AmpStory',
    'AmusementPark',
    'AnalysisNewsArticle',
    'AnatomicalStructure',
    'AnatomicalSystem',
    'AnimalShelter',
    'Answer',
    'Apartment',
    'ApartmentComplex',
    'AppendAction',
    'ApplyAction',
    'ApprovedIndication',
    'Aquarium',
    'ArchiveComponent',
    'ArchiveOrganization',
    'ArriveAction',
    'ArtGallery',
    'Artery',
    'Article',
    'AskAction',
    'AskPublicNewsArticle',
    'AssessAction',
    'AssignAction',
    'Atlas',
    'Attorney',
    'Audience',
    'AudioObject',
    'AudioObjectSnapshot',
    'Audiobook',
    'AuthorizeAction',
    'AutoBodyShop',
    'AutoDealer',
    'AutoPartsStore',
    'AutoRental',
    'AutoRepair',
    'AutoWash',
    'AutomatedTeller',
    'AutomotiveBusiness',
    'BackgroundNewsArticle',
    'Bakery',
    'BankAccount',
    'BankOrCreditUnion',
    'BarOrPub',
    'Barcode',
    'Beach',
    'BeautySalon',
    'BedAndBreakfast',
    'BedDetails',
    'BedType',
    'BefriendAction',
    'BikeStore',
    'BioChemEntity',
    'Blog',
    'BlogPosting',
    'BloodTest',
    
    'BoatReservation',
    'BoatTerminal',
    'BoatTrip',
    
    'BodyOfWater',
    'Bone',
    'Book',
    
    'BookSeries',
    'BookStore',
    'BookmarkAction',
    'BorrowAction',
    'BowlingAlley',
    'BrainStructure',
    'Brand',
    'BreadcrumbList',
    'Brewery',
    'Bridge',
    'BroadcastChannel',
    'BroadcastEvent',
    'BroadcastFrequencySpecification',
    'BroadcastService',
    'BrokerageAccount',
    'BuddhistTemple',
    'BusOrCoach',
    'BusReservation',
    'BusStation',
    'BusStop',
    'BusTrip',
    'BusinessAudience',
    'BusinessEntityType',
    'BusinessEvent',
    'BusinessFunction',
    'BuyAction',
    'CDCPMDRecord',
    'CableOrSatelliteService',
    'CafeOrCoffeeShop',
    'Campground',
    'CampingPitch',
    'Canal',
    'CancelAction',
    'Car',
    
    'Casino',
    'CategoryCode',
    'CategoryCodeSet',
    'CatholicChurch',
    'Cemetery',
    'Certification',
    
    'Chapter',
    'CheckAction',
    'CheckInAction',
    'CheckOutAction',
    'CheckoutPage',
    'ChemicalSubstance',
    'ChildCare',
    'ChildrensEvent',
    'ChooseAction',
    'Church',
    'City',
    'CityHall',
    'CivicStructure',
    'Claim',
    'ClaimReview',
    'Class',
    'Clip',
    'ClothingStore',
    'Code',
    'Collection',
    'CollectionPage',
    'CollegeOrUniversity',
    'ComedyClub',
    'ComedyEvent',
    'ComicCoverArt',
    'ComicIssue',
    'ComicSeries',
    'ComicStory',
    'Comment',
    'CommentAction',
    'CommunicateAction',
    'CompleteDataFeed',
    'CompoundPriceSpecification',
    'ComputerLanguage',
    'ComputerStore',
    'ConfirmAction',
    'Consortium',
    'ConstraintNode',
    'ConsumeAction',
    'ContactPage',
    'ContactPoint',
    
    'Continent',
    'ControlAction',
    'ConvenienceStore',
    'Conversation',
    'CookAction',
    'Cooperative',
    'Corporation',
    'CorrectionComment',
    'Country',
    'Course',
    'CourseInstance',
    'Courthouse',
    'CoverArt',
    'CovidTestingFacility',
    'CreateAction',
    'CreativeWork',
    'CreativeWorkSeason',
    'CreativeWorkSeries',
    'CreditCard',
    'Crematorium',
    'CriticReview',
    'CssSelectorType',
    'CurrencyConversionService',
    'DDxElement',
    'DanceEvent',
    'DanceGroup',
    'DataCatalog',
    'DataDownload',
    'DataFeed',
    'DataFeedItem',
    'DataType',
    'Dataset',
    'DatedMoneySpecification',
    
    'DaySpa',
    'DeactivateAction',
    'DefenceEstablishment',
    'DefinedRegion',
    'DefinedTerm',
    'DefinedTermSet',
    'DeleteAction',
    'DeliveryChargeSpecification',
    'DeliveryEvent',
    
    'Demand',
    'Dentist',
    'DepartAction',
    'DepartmentStore',
    'DepositAccount',
    'DiagnosticLab',
    'DiagnosticProcedure',
    'Diet',
    'DietarySupplement',
    'DigitalDocument',
    'DigitalDocumentPermission',
    
    
    'DisagreeAction',
    'DiscoverAction',
    'DiscussionForumPosting',
    'DislikeAction',
    'Distance',
    'Distillery',
    'DonateAction',
    'DoseSchedule',
    'DownloadAction',
    'DrawAction',
    'Drawing',
    'DrinkAction',
    
    'Drug',
    'DrugClass',
    'DrugCost',
    
    'DrugLegalStatus',
    
    
    'DrugStrength',
    'DryCleaningOrLaundry',
    'Duration',
    
    'EatAction',
    'EducationEvent',
    'EducationalAudience',
    'EducationalOccupationalCredential',
    'EducationalOccupationalProgram',
    'EducationalOrganization',
    'Electrician',
    'ElectronicsStore',
    'ElementarySchool',
    'EmailMessage',
    'Embassy',
    'EmergencyService',
    'EmployeeRole',
    'EmployerAggregateRating',
    'EmployerReview',
    'EmploymentAgency',
    'EndorseAction',
    'EndorsementRating',
    'Energy',
    'EnergyConsumptionDetails',
    'EnergyEfficiencyEnumeration',
    
    'EngineSpecification',
    'EntertainmentBusiness',
    'EntryPoint',
    'Enumeration',
    'Episode',
    'Event',
    
    'EventReservation',
    'EventSeries',
    
    'EventVenue',
    'ExchangeRateSpecification',
    'ExerciseAction',
    'ExerciseGym',
    'ExercisePlan',
    'ExhibitionEvent',
    'FAQPage',
    'FMRadioChannel',
    'FastFoodRestaurant',
    'Festival',
    'FilmAction',
    'FinancialIncentive',
    'FinancialProduct',
    'FinancialService',
    'FindAction',
    'FireStation',
    'Flight',
    'FlightReservation',
    'Float',
    'FloorPlan',
    'Florist',
    'FollowAction',
    'FoodEstablishment',
    'FoodEstablishmentReservation',
    'FoodEvent',
    'FoodService',
    
    'FundingAgency',
    'FundingScheme',
    'FurnitureStore',
    'Game',
    
    
    'GameServer',
    
    'GardenStore',
    'GasStation',
    'GatedResidenceCommunity',
    
    'Gene',
    'GeneralContractor',
    'GeoCircle',
    'GeoCoordinates',
    'GeoShape',
    'GeospatialGeometry',
    'GiveAction',
    'GolfCourse',
    
    'GovernmentBuilding',
    'GovernmentOffice',
    'GovernmentOrganization',
    'GovernmentPermit',
    'GovernmentService',
    'Grant',
    'GroceryStore',
    'Guide',
    'HVACBusiness',
    'Hackathon',
    'HairSalon',
    'HardwareStore',
    'HealthAndBeautyBusiness',
    
    'HealthClub',
    'HealthInsurancePlan',
    'HealthPlanCostSharingSpecification',
    'HealthPlanFormulary',
    'HealthPlanNetwork',
    'HealthTopicContent',
    'HighSchool',
    'HinduTemple',
    'HobbyShop',
    'HomeAndConstructionBusiness',
    'HomeGoodsStore',
    'Hospital',
    'Hostel',
    'Hotel',
    'HotelRoom',
    'House',
    'HousePainter',
    'HowTo',
    'HowToDirection',
    'HowToItem',
    'HowToSection',
    'HowToStep',
    'HowToSupply',
    'HowToTip',
    'HowToTool',
    'HyperToc',
    'HyperTocEntry',
    
    'IceCreamShop',
    'IgnoreAction',
    'ImageGallery',
    'ImageObject',
    'ImageObjectSnapshot',
    'ImagingTest',
    
    
    
    'IndividualPhysician',
    'IndividualProduct',
    
    'InfectiousDisease',
    'InformAction',
    'InsertAction',
    'InstallAction',
    'InsuranceAgency',
    'Intangible',
    'Integer',
    'InteractAction',
    'InteractionCounter',
    'InternetCafe',
    'InvestmentFund',
    'InvestmentOrDeposit',
    'InviteAction',
    'Invoice',
    
    'ItemList',
    
    'ItemPage',
    'JewelryStore',
    'JobPosting',
    'JoinAction',
    'Joint',
    'LakeBodyOfWater',
    'Landform',
    'LandmarksOrHistoricalBuildings',
    'Language',
    'LearningResource',
    'LeaveAction',
    
    'LegalService',
    
    'Legislation',
    'LegislationObject',
    'LegislativeBuilding',
    'LendAction',
    'Library',
    'LibrarySystem',
    'LifestyleModification',
    'Ligament',
    'LikeAction',
    'LinkRole',
    'LiquorStore',
    'ListItem',
    'ListenAction',
    'LiteraryEvent',
    'LiveBlogPosting',
    'LoanOrCredit',
    'LocalBusiness',
    'LocationFeatureSpecification',
    'Locksmith',
    'LodgingBusiness',
    'LodgingReservation',
    'LoseAction',
    'LymphaticVessel',
    'Manuscript',
    'Map',
    
    'MarryAction',
    'Mass',
    'MathSolver',
    'MaximumDoseSchedule',
    
    'MeasurementTypeEnumeration',
    'MediaEnumeration',
    'MediaGallery',
    
    'MediaObject',
    'MediaReview',
    'MediaReviewItem',
    'MediaSubscription',
    'MedicalAudience',
    
    'MedicalBusiness',
    'MedicalCause',
    'MedicalClinic',
    'MedicalCode',
    'MedicalCondition',
    'MedicalConditionStage',
    'MedicalContraindication',
    'MedicalDevice',
    
    'MedicalEntity',
    'MedicalEnumeration',
    
    'MedicalGuideline',
    'MedicalGuidelineContraindication',
    'MedicalGuidelineRecommendation',
    
    'MedicalIndication',
    'MedicalIntangible',
    'MedicalObservationalStudy',
    
    'MedicalOrganization',
    'MedicalProcedure',
    
    'MedicalRiskCalculator',
    'MedicalRiskEstimator',
    'MedicalRiskFactor',
    'MedicalRiskScore',
    'MedicalScholarlyArticle',
    'MedicalSign',
    'MedicalSignOrSymptom',
    
    'MedicalStudy',
    
    'MedicalSymptom',
    'MedicalTest',
    'MedicalTestPanel',
    'MedicalTherapy',
    'MedicalTrial',
    
    'MedicalWebPage',
    
    'MeetingRoom',
    'MemberProgram',
    'MemberProgramTier',
    'MensClothingStore',
    'Menu',
    'MenuItem',
    'MenuSection',
    
    'MerchantReturnPolicy',
    'MerchantReturnPolicySeasonalOverride',
    'Message',
    'MiddleSchool',
    'MobileApplication',
    'MobilePhoneStore',
    'MolecularEntity',
    'MonetaryAmount',
    'MonetaryAmountDistribution',
    'MonetaryGrant',
    'MoneyTransfer',
    'MortgageLoan',
    'Mosque',
    'Motel',
    'Motorcycle',
    'MotorcycleDealer',
    'MotorcycleRepair',
    'MotorizedBicycle',
    'Mountain',
    'MoveAction',
    'Movie',
    'MovieClip',
    'MovieRentalStore',
    'MovieSeries',
    'MovieTheater',
    'MovingCompany',
    'Muscle',
    'Museum',
    'MusicAlbum',
    
    
    'MusicComposition',
    'MusicEvent',
    'MusicGroup',
    'MusicPlaylist',
    'MusicRecording',
    'MusicRelease',
    
    'MusicStore',
    'MusicVenue',
    'MusicVideoObject',
    'NGO',
    
    'NailSalon',
    'Nerve',
    'NewsArticle',
    'NewsMediaOrganization',
    'Newspaper',
    'NightClub',
    'NonprofitType',
    'Notary',
    'NoteDigitalDocument',
    'NutritionInformation',
    'Observation',
    'Occupation',
    'OccupationalExperienceRequirements',
    'OccupationalTherapy',
    'OceanBodyOfWater',
    'Offer',
    'OfferCatalog',
    'OfferForLease',
    'OfferForPurchase',
    
    'OfferShippingDetails',
    'OfficeEquipmentStore',
    'OnDemandEvent',
    'OnlineBusiness',
    'OnlineStore',
    'OpeningHoursSpecification',
    'OpinionNewsArticle',
    'Optician',
    'Order',
    'OrderAction',
    'OrderItem',
    
    'Organization',
    'OrganizationRole',
    'OrganizeAction',
    'OutletStore',
    'OwnershipInfo',
    'PaintAction',
    'Painting',
    'PalliativeProcedure',
    'ParcelDelivery',
    'ParentAudience',
    'Park',
    'ParkingFacility',
    'PathologyTest',
    'Patient',
    'PawnShop',
    'PayAction',
    'PaymentCard',
    'PaymentChargeSpecification',
    'PaymentMethod',
    
    'PaymentService',
    
    'PeopleAudience',
    'PerformAction',
    'PerformanceRole',
    'PerformingArtsTheater',
    'PerformingGroup',
    'Periodical',
    'Permit',
    'Person',
    'PetStore',
    'Pharmacy',
    'Photograph',
    'PhotographAction',
    'PhysicalActivity',
    
    
    'PhysicalTherapy',
    'Physician',
    'PhysiciansOffice',
    'Place',
    'PlaceOfWorship',
    'PlanAction',
    'Play',
    'PlayAction',
    'PlayGameAction',
    'Playground',
    'Plumber',
    'PodcastEpisode',
    'PodcastSeason',
    'PodcastSeries',
    'PoliceStation',
    'PoliticalParty',
    'Pond',
    'PostOffice',
    'PostalAddress',
    'PostalCodeRangeSpecification',
    'Poster',
    'PreOrderAction',
    'PrependAction',
    'Preschool',
    'PresentationDigitalDocument',
    'PreventionIndication',
    
    'PriceSpecification',
    
    'Product',
    'ProductCollection',
    'ProductGroup',
    'ProductModel',
    'ProfessionalService',
    'ProfilePage',
    'ProgramMembership',
    'Project',
    'PronounceableText',
    'Property',
    'PropertyValue',
    'PropertyValueSpecification',
    'Protein',
    'PsychologicalTreatment',
    'PublicSwimmingPool',
    'PublicToilet',
    'PublicationEvent',
    'PublicationIssue',
    'PublicationVolume',
    
    'QAPage',
    'QualitativeValue',
    'QuantitativeValue',
    'QuantitativeValueDistribution',
    'Quantity',
    'Question',
    'Quiz',
    'Quotation',
    'QuoteAction',
    'RVPark',
    'RadiationTherapy',
    'RadioBroadcastService',
    'RadioChannel',
    'RadioClip',
    'RadioEpisode',
    'RadioSeason',
    'RadioSeries',
    'RadioStation',
    'Rating',
    'ReactAction',
    'ReadAction',
    'RealEstateAgent',
    'RealEstateListing',
    'ReceiveAction',
    'Recipe',
    'Recommendation',
    'RecommendedDoseSchedule',
    'RecyclingCenter',
    
    'RegisterAction',
    'RejectAction',
    'RentAction',
    'RentalCarReservation',
    'RepaymentSpecification',
    'ReplaceAction',
    'ReplyAction',
    'Report',
    'ReportageNewsArticle',
    'ReportedDoseSchedule',
    'ResearchOrganization',
    'ResearchProject',
    'Researcher',
    'Reservation',
    'ReservationPackage',
    
    'ReserveAction',
    'Reservoir',
    'Residence',
    'Resort',
    'Restaurant',
    
    'ResumeAction',
    'ReturnAction',
    
    
    
    'Review',
    'ReviewAction',
    'ReviewNewsArticle',
    'RiverBodyOfWater',
    'Role',
    'RoofingContractor',
    'Room',
    'RsvpAction',
    
    'SaleEvent',
    'SatiricalArticle',
    'Schedule',
    'ScheduleAction',
    'ScholarlyArticle',
    'School',
    'SchoolDistrict',
    'ScreeningEvent',
    'Sculpture',
    'SeaBodyOfWater',
    'SearchAction',
    'SearchRescueOrganization',
    'SearchResultsPage',
    'Season',
    'Seat',
    'SeekToAction',
    'SelfStorage',
    'SellAction',
    'SendAction',
    'Series',
    'Service',
    'ServiceChannel',
    'ServicePeriod',
    'ShareAction',
    'SheetMusic',
    'ShippingConditions',
    'ShippingDeliveryTime',
    'ShippingRateSettings',
    'ShippingService',
    'ShoeStore',
    'ShoppingCenter',
    'ShortStory',
    'SingleFamilyResidence',
    'SiteNavigationElement',
    'SizeGroupEnumeration',
    'SizeSpecification',
    
    'SkiResort',
    'SocialEvent',
    'SocialMediaPosting',
    'SoftwareApplication',
    'SoftwareSourceCode',
    'SolveMathAction',
    'SomeProducts',
    'SpeakableSpecification',
    'SpecialAnnouncement',
    'Specialty',
    'SportingGoodsStore',
    'SportsActivityLocation',
    'SportsClub',
    'SportsEvent',
    'SportsOrganization',
    'SportsTeam',
    'SpreadsheetDigitalDocument',
    'StadiumOrArena',
    'State',
    'Statement',
    'StatisticalPopulation',
    'StatisticalVariable',
    'StatusEnumeration',
    
    'Store',
    'StructuredValue',
    'SubscribeAction',
    'Substance',
    'SubwayStation',
    'Suite',
    'SuperficialAnatomy',
    'SurgicalProcedure',
    'SuspendAction',
    'Syllabus',
    'Synagogue',
    'TVClip',
    'TVEpisode',
    'TVSeason',
    'TVSeries',
    'Table',
    'TakeAction',
    'TattooParlor',
    'Taxi',
    'TaxiReservation',
    'TaxiService',
    'TaxiStand',
    'Taxon',
    'TechArticle',
    'TelevisionChannel',
    'TelevisionStation',
    'TennisComplex',
    'TextDigitalDocument',
    'TextObject',
    'TheaterEvent',
    'TheaterGroup',
    'TherapeuticProcedure',
    'Thesis',
    'Thing',
    'Ticket',
    'TieAction',
    
    'TipAction',
    'TireShop',
    'TouristAttraction',
    'TouristDestination',
    'TouristInformationCenter',
    'TouristTrip',
    'ToyStore',
    'TrackAction',
    'TradeAction',
    'TrainReservation',
    'TrainStation',
    'TrainTrip',
    'TransferAction',
    'TravelAction',
    'TravelAgency',
    'TreatmentIndication',
    'Trip',
    'TypeAndQuantityNode',
    
    'URL',
    
    'UnRegisterAction',
    'UnitPriceSpecification',
    'UpdateAction',
    'UseAction',
    'UserBlocks',
    'UserCheckins',
    'UserComments',
    'UserDownloads',
    'UserInteraction',
    'UserLikes',
    'UserPageVisits',
    'UserPlays',
    'UserPlusOnes',
    'UserReview',
    'UserTweets',
    'VacationRental',
    'Vehicle',
    'Vein',
    'Vessel',
    'VeterinaryCare',
    'VideoGallery',
    'VideoGame',
    'VideoGameClip',
    'VideoGameSeries',
    'VideoObject',
    'VideoObjectSnapshot',
    'ViewAction',
    'VirtualLocation',
    'VisualArtsEvent',
    'VisualArtwork',
    'VitalSign',
    'Volcano',
    'VoteAction',
    'WPAdBlock',
    'WPFooter',
    'WPHeader',
    'WPSideBar',
    'WantAction',
    'WarrantyPromise',
    'WarrantyScope',
    'WatchAction',
    'Waterfall',
    'WearAction',
    
    
    
    'WebAPI',
    'WebApplication',
    'WebContent',
    'WebPage',
    'WebPageElement',
    'WebSite',
    'WholesaleStore',
    'WinAction',
    'Winery',
    'WorkBasedProgram',
    'WorkersUnion',
    'WriteAction',
    'XPathType',
    'Zoo',
]
