# Generated by Django 5.2 on 2025-05-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0003_alter_scriptconfig_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptconfig',
            name='metric_namespace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
