"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lumos_lcm_control(object):
    __slots__ = ["state", "x", "y", "yaw"]

    def __init__(self):
        self.state = 0
        self.x = 0.0
        self.y = 0.0
        self.yaw = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(lumos_lcm_control._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bfff", self.state, self.x, self.y, self.yaw))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lumos_lcm_control._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lumos_lcm_control._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lumos_lcm_control()
        self.state, self.x, self.y, self.yaw = struct.unpack(">bfff", buf.read(13))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lumos_lcm_control in parents: return 0
        tmphash = (0x71818325a17d922e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lumos_lcm_control._packed_fingerprint is None:
            lumos_lcm_control._packed_fingerprint = struct.pack(">Q", lumos_lcm_control._get_hash_recursive([]))
        return lumos_lcm_control._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

