# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: int32.proto
# plugin: python-betterproto
# This file has been @generated

__all__ = ("Test",)


from dataclasses import dataclass

import betterproto_fw


@dataclass(eq=False, repr=False)
class Test(betterproto_fw.Message):
    """Some documentation about the Test message."""

    positive: int = betterproto_fw.int32_field(1)
    """Some documentation about the count."""

    negative: int = betterproto_fw.int32_field(2)
    """
    
    """
