"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class upper_body_cmd_package(object):
    __slots__ = ["isUsed", "control_mode", "jointPosVec", "jointSpeedVec", "jointCurrentVec", "body_yaw"]

    def __init__(self):
        self.isUsed = 0
        self.control_mode = [ 0 for dim0 in range(28) ]
        self.jointPosVec = [ 0.0 for dim0 in range(28) ]
        self.jointSpeedVec = [ 0.0 for dim0 in range(28) ]
        self.jointCurrentVec = [ 0.0 for dim0 in range(28) ]
        self.body_yaw = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(upper_body_cmd_package._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.isUsed))
        buf.write(struct.pack('>28i', *self.control_mode[:28]))
        buf.write(struct.pack('>28f', *self.jointPosVec[:28]))
        buf.write(struct.pack('>28f', *self.jointSpeedVec[:28]))
        buf.write(struct.pack('>28f', *self.jointCurrentVec[:28]))
        buf.write(struct.pack(">f", self.body_yaw))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != upper_body_cmd_package._get_packed_fingerprint():
            raise ValueError("Decode error")
        return upper_body_cmd_package._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = upper_body_cmd_package()
        self.isUsed = struct.unpack(">i", buf.read(4))[0]
        self.control_mode = struct.unpack('>28i', buf.read(112))
        self.jointPosVec = struct.unpack('>28f', buf.read(112))
        self.jointSpeedVec = struct.unpack('>28f', buf.read(112))
        self.jointCurrentVec = struct.unpack('>28f', buf.read(112))
        self.body_yaw = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if upper_body_cmd_package in parents: return 0
        tmphash = (0x986309b48c31913a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if upper_body_cmd_package._packed_fingerprint is None:
            upper_body_cmd_package._packed_fingerprint = struct.pack(">Q", upper_body_cmd_package._get_hash_recursive([]))
        return upper_body_cmd_package._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

