# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from akoyaapisv240.api_helper import APIHelper


class CodeAndAmount(object):

    """Implementation of the 'Code and Amount' model.

    Code and amount pair used on IRS W-2, K-1, etc.

    Attributes:
        code (str): Code
        amount (float): Amount

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "code": 'code',
        "amount": 'amount'
    }

    _optionals = [
        'code',
        'amount',
    ]

    def __init__(self,
                 code=APIHelper.SKIP,
                 amount=APIHelper.SKIP):
        """Constructor for the CodeAndAmount class"""

        # Initialize members of the class
        if code is not APIHelper.SKIP:
            self.code = code 
        if amount is not APIHelper.SKIP:
            self.amount = amount 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        code = dictionary.get("code") if dictionary.get("code") else APIHelper.SKIP
        amount = dictionary.get("amount") if dictionary.get("amount") else APIHelper.SKIP
        # Return an object of this model
        return cls(code,
                   amount)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'code={(self.code if hasattr(self, "code") else None)!r}, '
                f'amount={(self.amount if hasattr(self, "amount") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'code={(self.code if hasattr(self, "code") else None)!s}, '
                f'amount={(self.amount if hasattr(self, "amount") else None)!s})')
