# -*- coding: utf-8 -*-

"""
akoyaapisv240

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TelephoneNumberTypeEnum(object):

    """Implementation of the 'Telephone Number Type' enum.

    Purpose or type of telephone number

    Attributes:
        BUSINESS: The enum member of type str.
        CELL: The enum member of type str.
        FAX: The enum member of type str.
        HOME: The enum member of type str.

    """
    BUSINESS = 'BUSINESS'

    CELL = 'CELL'

    FAX = 'FAX'

    HOME = 'HOME'

