# Generated by ariadne-codegen
# Source: python/atoti-client/graphql/operations.gql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import LevelType


class FindLevelAcrossHierarchies(BaseModel):
    data_model: Optional["FindLevelAcrossHierarchiesDataModel"] = Field(
        alias="dataModel"
    )


class FindLevelAcrossHierarchiesDataModel(BaseModel):
    cube: Optional["FindLevelAcrossHierarchiesDataModelCube"]


class FindLevelAcrossHierarchiesDataModelCube(BaseModel):
    dimensions: List["FindLevelAcrossHierarchiesDataModelCubeDimensions"]


class FindLevelAcrossHierarchiesDataModelCubeDimensions(BaseModel):
    hierarchies: List["FindLevelAcrossHierarchiesDataModelCubeDimensionsHierarchies"]
    name: str


class FindLevelAcrossHierarchiesDataModelCubeDimensionsHierarchies(BaseModel):
    level: Optional["FindLevelAcrossHierarchiesDataModelCubeDimensionsHierarchiesLevel"]
    name: str


class FindLevelAcrossHierarchiesDataModelCubeDimensionsHierarchiesLevel(BaseModel):
    name: str
    type: LevelType


FindLevelAcrossHierarchies.model_rebuild()
FindLevelAcrossHierarchiesDataModel.model_rebuild()
FindLevelAcrossHierarchiesDataModelCube.model_rebuild()
FindLevelAcrossHierarchiesDataModelCubeDimensions.model_rebuild()
FindLevelAcrossHierarchiesDataModelCubeDimensionsHierarchies.model_rebuild()
