# Generated by ariadne-codegen
# Source: python/atoti-client/graphql/operations.gql

from typing import Annotated, List, Literal, Union

from pydantic import Field

from .._constant import Constant
from .base_model import BaseModel
from .enums import (
    CubeRestrictionIsInConditionOperator,
    CubeRestrictionRelationalConditionOperator,
)


class TableIdentifierFragment(BaseModel):
    name: str


class ColumnIdentifierFragment(BaseModel):
    name: str
    table: "ColumnIdentifierFragmentTable"


class ColumnIdentifierFragmentTable(TableIdentifierFragment):
    pass


class CubeIdentifierFragment(BaseModel):
    name: str


class DimensionIdentifierFragment(BaseModel):
    name: str


class HierarchyIdentifierFragment(BaseModel):
    dimension: "HierarchyIdentifierFragmentDimension"
    name: str


class HierarchyIdentifierFragmentDimension(DimensionIdentifierFragment):
    pass


class LevelIdentifierFragment(BaseModel):
    hierarchy: "LevelIdentifierFragmentHierarchy"
    name: str


class LevelIdentifierFragmentHierarchy(HierarchyIdentifierFragment):
    pass


class CubeRestrictionFragment(BaseModel):
    condition: List[
        List[
            Annotated[
                Union[
                    "CubeRestrictionFragmentConditionCubeRestrictionIsInCondition",
                    "CubeRestrictionFragmentConditionCubeRestrictionRelationalCondition",
                ],
                Field(discriminator="typename__"),
            ]
        ]
    ]


class CubeRestrictionFragmentConditionCubeRestrictionIsInCondition(BaseModel):
    typename__: Literal["CubeRestrictionIsInCondition"] = Field(alias="__typename")
    elements: List[Constant]
    is_in_operator: CubeRestrictionIsInConditionOperator = Field(alias="isInOperator")
    level: "CubeRestrictionFragmentConditionCubeRestrictionIsInConditionLevel"


class CubeRestrictionFragmentConditionCubeRestrictionIsInConditionLevel(
    LevelIdentifierFragment
):
    pass


class CubeRestrictionFragmentConditionCubeRestrictionRelationalCondition(BaseModel):
    typename__: Literal["CubeRestrictionRelationalCondition"] = Field(
        alias="__typename"
    )
    level: "CubeRestrictionFragmentConditionCubeRestrictionRelationalConditionLevel"
    relational_operator: CubeRestrictionRelationalConditionOperator = Field(
        alias="relationalOperator"
    )
    target: Constant


class CubeRestrictionFragmentConditionCubeRestrictionRelationalConditionLevel(
    LevelIdentifierFragment
):
    pass


class JoinIdentifierFragment(BaseModel):
    name: str
    source: "JoinIdentifierFragmentSource"


class JoinIdentifierFragmentSource(TableIdentifierFragment):
    pass


class MeasureIdentifierFragment(BaseModel):
    name: str


class SelectionFieldIdentifierFragment(BaseModel):
    column: "SelectionFieldIdentifierFragmentColumn"
    joins: List["SelectionFieldIdentifierFragmentJoins"]


class SelectionFieldIdentifierFragmentColumn(ColumnIdentifierFragment):
    pass


class SelectionFieldIdentifierFragmentJoins(JoinIdentifierFragment):
    pass


TableIdentifierFragment.model_rebuild()
ColumnIdentifierFragment.model_rebuild()
CubeIdentifierFragment.model_rebuild()
DimensionIdentifierFragment.model_rebuild()
HierarchyIdentifierFragment.model_rebuild()
LevelIdentifierFragment.model_rebuild()
CubeRestrictionFragment.model_rebuild()
JoinIdentifierFragment.model_rebuild()
MeasureIdentifierFragment.model_rebuild()
SelectionFieldIdentifierFragment.model_rebuild()
