# Generated by ariadne-codegen
# Source: python/atoti-client/graphql/operations.gql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import SelectionFieldIdentifierFragment


class GetLevelSelectionField(BaseModel):
    data_model: Optional["GetLevelSelectionFieldDataModel"] = Field(alias="dataModel")


class GetLevelSelectionFieldDataModel(BaseModel):
    cube: Optional["GetLevelSelectionFieldDataModelCube"]


class GetLevelSelectionFieldDataModelCube(BaseModel):
    dimension: Optional["GetLevelSelectionFieldDataModelCubeDimension"]


class GetLevelSelectionFieldDataModelCubeDimension(BaseModel):
    hierarchy: Optional["GetLevelSelectionFieldDataModelCubeDimensionHierarchy"]


class GetLevelSelectionFieldDataModelCubeDimensionHierarchy(BaseModel):
    level: Optional["GetLevelSelectionFieldDataModelCubeDimensionHierarchyLevel"]


class GetLevelSelectionFieldDataModelCubeDimensionHierarchyLevel(BaseModel):
    selection_field: Optional[
        "GetLevelSelectionFieldDataModelCubeDimensionHierarchyLevelSelectionField"
    ] = Field(alias="selectionField")


class GetLevelSelectionFieldDataModelCubeDimensionHierarchyLevelSelectionField(
    SelectionFieldIdentifierFragment
):
    pass


GetLevelSelectionField.model_rebuild()
GetLevelSelectionFieldDataModel.model_rebuild()
GetLevelSelectionFieldDataModelCube.model_rebuild()
GetLevelSelectionFieldDataModelCubeDimension.model_rebuild()
GetLevelSelectionFieldDataModelCubeDimensionHierarchy.model_rebuild()
GetLevelSelectionFieldDataModelCubeDimensionHierarchyLevel.model_rebuild()
