# Generated by ariadne-codegen
# Source: python/atoti-client/graphql/operations.gql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import CubeRestrictionFragment


class GetCubeRestriction(BaseModel):
    data_model: Optional["GetCubeRestrictionDataModel"] = Field(alias="dataModel")


class GetCubeRestrictionDataModel(BaseModel):
    cube: Optional["GetCubeRestrictionDataModelCube"]


class GetCubeRestrictionDataModelCube(BaseModel):
    restriction: Optional["GetCubeRestrictionDataModelCubeRestriction"]


class GetCubeRestrictionDataModelCubeRestriction(CubeRestrictionFragment):
    pass


GetCubeRestriction.model_rebuild()
GetCubeRestrictionDataModel.model_rebuild()
GetCubeRestrictionDataModelCube.model_rebuild()
