# Generated by ariadne-codegen
# Source: python/atoti-client/graphql/operations.gql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetHierarchyAreMembersIndexedByName(BaseModel):
    data_model: Optional["GetHierarchyAreMembersIndexedByNameDataModel"] = Field(
        alias="dataModel"
    )


class GetHierarchyAreMembersIndexedByNameDataModel(BaseModel):
    cube: Optional["GetHierarchyAreMembersIndexedByNameDataModelCube"]


class GetHierarchyAreMembersIndexedByNameDataModelCube(BaseModel):
    dimension: Optional["GetHierarchyAreMembersIndexedByNameDataModelCubeDimension"]


class GetHierarchyAreMembersIndexedByNameDataModelCubeDimension(BaseModel):
    hierarchy: Optional[
        "GetHierarchyAreMembersIndexedByNameDataModelCubeDimensionHierarchy"
    ]


class GetHierarchyAreMembersIndexedByNameDataModelCubeDimensionHierarchy(BaseModel):
    are_members_indexed_by_name: bool = Field(alias="areMembersIndexedByName")


GetHierarchyAreMembersIndexedByName.model_rebuild()
GetHierarchyAreMembersIndexedByNameDataModel.model_rebuild()
GetHierarchyAreMembersIndexedByNameDataModelCube.model_rebuild()
GetHierarchyAreMembersIndexedByNameDataModelCubeDimension.model_rebuild()
