# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: googletypes_struct.proto
# plugin: python-betterproto
# This file has been @generated

__all__ = ("Test",)


from pydantic.dataclasses import dataclass

import betterproto_fw


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class Test(betterproto_fw.Message):
    """ """

    struct: "betterproto_fw_lib_pydantic_google_protobuf.Struct" = (
        betterproto_fw.message_field(1)
    )
    """
    
    """


import betterproto_fw.lib.pydantic.google.protobuf as betterproto_fw_lib_pydantic_google_protobuf
