# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto3_field_presence_oneof.proto
# plugin: python-betterproto
# This file has been @generated

__all__ = (
    "Test",
    "InnerNested",
    "Nested",
    "WithOptional",
)


from dataclasses import dataclass
from typing import (
    Optional,
)

import betterproto_fw


@dataclass(eq=False, repr=False)
class Test(betterproto_fw.Message):
    """ """

    nested: "Nested" = betterproto_fw.message_field(1, group="kind")
    """
    
    """

    with_optional: "WithOptional" = betterproto_fw.message_field(2, group="kind")
    """
    
    """


@dataclass(eq=False, repr=False)
class InnerNested(betterproto_fw.Message):
    """ """

    a: Optional[bool] = betterproto_fw.bool_field(1, optional=True)
    """
    
    """


@dataclass(eq=False, repr=False)
class Nested(betterproto_fw.Message):
    """ """

    inner: "InnerNested" = betterproto_fw.message_field(1)
    """
    
    """


@dataclass(eq=False, repr=False)
class WithOptional(betterproto_fw.Message):
    """ """

    b: Optional[bool] = betterproto_fw.bool_field(2, optional=True)
    """
    
    """
