# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: cousin.proto
# plugin: python-betterproto
# This file has been @generated

__all__ = ("CousinMessage",)


from pydantic.dataclasses import dataclass

import betterproto_fw


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class CousinMessage(betterproto_fw.Message):
    """ """

    pass
