# Generated by Django 5.2 on 2025-05-07 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canary', '0002_alter_scriptconfig_log_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptconfig',
            name='delay',
            field=models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(86400)]),
        ),
    ]
