# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: enum.proto
# plugin: python-betterproto
# This file has been @generated

__all__ = (
    "Choice",
    "ArithmeticOperator",
    "Test",
)


from dataclasses import dataclass
from typing import (
    List,
)

import betterproto_fw


class Choice(betterproto_fw.Enum):
    """ """

    ZERO = 0
    """
    
    """

    ONE = 1
    """
    
    """

    FOUR = 4
    """TWO = 2;"""

    THREE = 3
    """
    
    """


class ArithmeticOperator(betterproto_fw.Enum):
    """
    A "C" like enum with the enum name prefixed onto members, these should be stripped
    """

    NONE = 0
    """
    
    """

    PLUS = 1
    """
    
    """

    MINUS = 2
    """
    
    """

    _0_PREFIXED = 3
    """
    
    """


@dataclass(eq=False, repr=False)
class Test(betterproto_fw.Message):
    """
    Tests that enums are correctly serialized and that it correctly handles skipped and out-of-order enum values
    """

    choice: "Choice" = betterproto_fw.enum_field(1)
    """
    
    """

    choices: List["Choice"] = betterproto_fw.enum_field(2)
    """
    
    """
