# Generated by Django 4.2.20 on 2025-04-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_reg', '0002_usersettings_api_backend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='api_backend',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сервер API'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ API'),
        ),
    ]
