// The .hh version of this file is generated by CMake (see CMakeLists.txt).
#ifndef KARABO_UTIL_VERSIONHASH_HH
#define KARABO_UTIL_VERSIONHASH_HH

#define KARABO_VERSION "2.21.5"
#define KARABO_VERSION_NUM(major, minor, patch) major * 1'000'000 + minor * 1000 + patch
#define KARABO_VERSION_NUM_CURRENT 2 * 1'000'000 + 21 * 1000 + 5

#endif
