/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class dcm_foothold_planner_lcmt implements lcm.lcm.LCMEncodable
{
    public float p_WLeftFoot_ref[];
    public float p_WRightFoot_ref[];
    public float v_WLeftFoot_ref[];
    public float v_WRightFoot_ref[];
    public float a_WLeftFoot_ref[];
    public float a_WRightFoot_ref[];
    public float r_cmp_ref[];
    public float p_WStanceFoot_ref[];
    public float foothold_adjustment[];
 
    public dcm_foothold_planner_lcmt()
    {
        p_WLeftFoot_ref = new float[3];
        p_WRightFoot_ref = new float[3];
        v_WLeftFoot_ref = new float[3];
        v_WRightFoot_ref = new float[3];
        a_WLeftFoot_ref = new float[3];
        a_WRightFoot_ref = new float[3];
        r_cmp_ref = new float[3];
        p_WStanceFoot_ref = new float[3];
        foothold_adjustment = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x2d0f46af39b1128eL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.dcm_foothold_planner_lcmt.class))
            return 0L;
 
        classes.add(lcmtypes.dcm_foothold_planner_lcmt.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.p_WLeftFoot_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.p_WRightFoot_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.v_WLeftFoot_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.v_WRightFoot_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.a_WLeftFoot_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.a_WRightFoot_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.r_cmp_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.p_WStanceFoot_ref[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.foothold_adjustment[a]); 
        }
 
    }
 
    public dcm_foothold_planner_lcmt(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public dcm_foothold_planner_lcmt(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.dcm_foothold_planner_lcmt _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.dcm_foothold_planner_lcmt o = new lcmtypes.dcm_foothold_planner_lcmt();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.p_WLeftFoot_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.p_WLeftFoot_ref[a] = ins.readFloat();
        }
 
        this.p_WRightFoot_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.p_WRightFoot_ref[a] = ins.readFloat();
        }
 
        this.v_WLeftFoot_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.v_WLeftFoot_ref[a] = ins.readFloat();
        }
 
        this.v_WRightFoot_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.v_WRightFoot_ref[a] = ins.readFloat();
        }
 
        this.a_WLeftFoot_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.a_WLeftFoot_ref[a] = ins.readFloat();
        }
 
        this.a_WRightFoot_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.a_WRightFoot_ref[a] = ins.readFloat();
        }
 
        this.r_cmp_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.r_cmp_ref[a] = ins.readFloat();
        }
 
        this.p_WStanceFoot_ref = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.p_WStanceFoot_ref[a] = ins.readFloat();
        }
 
        this.foothold_adjustment = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.foothold_adjustment[a] = ins.readFloat();
        }
 
    }
 
    public lcmtypes.dcm_foothold_planner_lcmt copy()
    {
        lcmtypes.dcm_foothold_planner_lcmt outobj = new lcmtypes.dcm_foothold_planner_lcmt();
        outobj.p_WLeftFoot_ref = new float[(int) 3];
        System.arraycopy(this.p_WLeftFoot_ref, 0, outobj.p_WLeftFoot_ref, 0, 3); 
        outobj.p_WRightFoot_ref = new float[(int) 3];
        System.arraycopy(this.p_WRightFoot_ref, 0, outobj.p_WRightFoot_ref, 0, 3); 
        outobj.v_WLeftFoot_ref = new float[(int) 3];
        System.arraycopy(this.v_WLeftFoot_ref, 0, outobj.v_WLeftFoot_ref, 0, 3); 
        outobj.v_WRightFoot_ref = new float[(int) 3];
        System.arraycopy(this.v_WRightFoot_ref, 0, outobj.v_WRightFoot_ref, 0, 3); 
        outobj.a_WLeftFoot_ref = new float[(int) 3];
        System.arraycopy(this.a_WLeftFoot_ref, 0, outobj.a_WLeftFoot_ref, 0, 3); 
        outobj.a_WRightFoot_ref = new float[(int) 3];
        System.arraycopy(this.a_WRightFoot_ref, 0, outobj.a_WRightFoot_ref, 0, 3); 
        outobj.r_cmp_ref = new float[(int) 3];
        System.arraycopy(this.r_cmp_ref, 0, outobj.r_cmp_ref, 0, 3); 
        outobj.p_WStanceFoot_ref = new float[(int) 3];
        System.arraycopy(this.p_WStanceFoot_ref, 0, outobj.p_WStanceFoot_ref, 0, 3); 
        outobj.foothold_adjustment = new float[(int) 3];
        System.arraycopy(this.foothold_adjustment, 0, outobj.foothold_adjustment, 0, 3); 
        return outobj;
    }
 
}

