# coding: utf-8

"""
    DataForSEO API documentation

    DataForSEO API is the starting point on your journey towards building powerful SEO software. With DataForSEO you can get all the data you need to build an efficient application while also saving your time and budget. DataForSEO API is using the REST technology for interchanging data between your application and our service. The data exchange is made through the widely used HTTP protocol, which allows applying our API to almost all programming languages.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dataforseo_client.models.keywords_data_bing_audience_estimation_task_get_task_info import KeywordsDataBingAudienceEstimationTaskGetTaskInfo

class TestKeywordsDataBingAudienceEstimationTaskGetTaskInfo(unittest.TestCase):
    """KeywordsDataBingAudienceEstimationTaskGetTaskInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KeywordsDataBingAudienceEstimationTaskGetTaskInfo:
        """Test KeywordsDataBingAudienceEstimationTaskGetTaskInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `KeywordsDataBingAudienceEstimationTaskGetTaskInfo`
        """
        model = KeywordsDataBingAudienceEstimationTaskGetTaskInfo()
        if include_optional:
            return KeywordsDataBingAudienceEstimationTaskGetTaskInfo(
                id = '',
                status_code = 56,
                status_message = '',
                time = '',
                cost = 1.337,
                result_count = 56,
                path = [
                    ''
                    ],
                data = dataforseo_client.models.data.data(),
                result = [
                    dataforseo_client.models.keywords_data_bing_audience_estimation_task_get_result_info.KeywordsDataBingAudienceEstimationTaskGetResultInfo(
                        est_impressions = dataforseo_client.models.est_info.EstInfo(
                            high = 56, 
                            low = 56, ), 
                        est_audience_size = dataforseo_client.models.est_info.EstInfo(
                            high = 56, 
                            low = 56, ), 
                        est_clicks = , 
                        est_spend = , 
                        est_cost_per_event = dataforseo_client.models.est_c_info.EstCInfo(
                            high = 1.337, 
                            low = 1.337, ), 
                        est_ctr = dataforseo_client.models.est_c_info.EstCInfo(
                            high = 1.337, 
                            low = 1.337, ), 
                        suggested_bid = 1.337, 
                        suggested_budget = 1.337, 
                        events_lost_to_bid = 56, 
                        events_lost_to_budget = 56, 
                        est_reach_audience_size = 56, 
                        est_reach_impressions = 56, 
                        currency = '', )
                    ]
            )
        else:
            return KeywordsDataBingAudienceEstimationTaskGetTaskInfo(
        )
        """

    def testKeywordsDataBingAudienceEstimationTaskGetTaskInfo(self):
        """Test KeywordsDataBingAudienceEstimationTaskGetTaskInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
